version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.16.2-browsers-legacy
        environment:
          NO_SANDBOX: true
    steps:
      - checkout
      - run:
          command: npm ci
      - run:
          command: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - dist

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
